/** Standard pack's names, equipment grants and active-use semantics live together. */
export const STANDARD_CARD_SPECS = [
  { id: 'sha', label: '杀', kind: 'basic', play: { targeting: 'attack' }, effect: 'attack' },
  { id: 'shan', label: '闪', kind: 'basic', play: { targeting: 'unplayable' }, effect: 'none' },
  { id: 'tao', label: '桃', kind: 'basic', play: { targeting: 'none', availability: 'wounded' }, effect: 'recover' },
  { id: 'bagua', label: '八卦阵', kind: 'equip', slot: 'armor', abilities: ['standard.bagua'], play: { targeting: 'none' }, effect: 'equip' },
  { id: 'jueying', label: '绝影', kind: 'equip', slot: 'plusHorse', abilities: ['standard.plusHorse'], play: { targeting: 'none' }, effect: 'equip' },
  { id: 'dilu', label: '的卢', kind: 'equip', slot: 'plusHorse', abilities: ['standard.plusHorse'], play: { targeting: 'none' }, effect: 'equip' },
  { id: 'zhuahuang', label: '爪黄飞电', kind: 'equip', slot: 'plusHorse', abilities: ['standard.plusHorse'], play: { targeting: 'none' }, effect: 'equip' },
  { id: 'chitu', label: '赤兔', kind: 'equip', slot: 'minusHorse', abilities: ['standard.minusHorse'], play: { targeting: 'none' }, effect: 'equip' },
  { id: 'dawan', label: '大宛', kind: 'equip', slot: 'minusHorse', abilities: ['standard.minusHorse'], play: { targeting: 'none' }, effect: 'equip' },
  { id: 'zixin', label: '紫骍', kind: 'equip', slot: 'minusHorse', abilities: ['standard.minusHorse'], play: { targeting: 'none' }, effect: 'equip' },
  { id: 'zhuge', label: '诸葛连弩', kind: 'equip', slot: 'weapon', range: 1, abilities: ['standard.zhuge'], play: { targeting: 'none' }, effect: 'equip' },
  { id: 'cixiong', label: '雌雄双股剑', kind: 'equip', slot: 'weapon', range: 2, abilities: ['standard.cixiong'], play: { targeting: 'none' }, effect: 'equip' },
  { id: 'qinggang', label: '青釭剑', kind: 'equip', slot: 'weapon', range: 2, abilities: ['standard.qinggang'], play: { targeting: 'none' }, effect: 'equip' },
  { id: 'qinglong', label: '青龙偃月刀', kind: 'equip', slot: 'weapon', range: 3, abilities: ['standard.qinglong'], play: { targeting: 'none' }, effect: 'equip' },
  { id: 'zhangba', label: '丈八蛇矛', kind: 'equip', slot: 'weapon', range: 3, abilities: ['standard.zhangba'], play: { targeting: 'none' }, effect: 'equip' },
  { id: 'guanshi', label: '贯石斧', kind: 'equip', slot: 'weapon', range: 3, abilities: ['standard.guanshi'], play: { targeting: 'none' }, effect: 'equip' },
  { id: 'fangtian', label: '方天画戟', kind: 'equip', slot: 'weapon', range: 4, abilities: ['standard.fangtian'], play: { targeting: 'none' }, effect: 'equip' },
  { id: 'qilin', label: '麒麟弓', kind: 'equip', slot: 'weapon', range: 5, abilities: ['standard.qilin'], play: { targeting: 'none' }, effect: 'equip' },
  { id: 'hanbing', label: '寒冰剑', kind: 'equip', slot: 'weapon', range: 2, abilities: ['standard.hanbing'], play: { targeting: 'none' }, effect: 'equip' },
  { id: 'renwang', label: '仁王盾', kind: 'equip', slot: 'armor', abilities: ['standard.renwang'], play: { targeting: 'none' }, effect: 'equip' },
  { id: 'wugu', label: '五谷丰登', kind: 'trick', play: { targeting: 'none', scope: 'all' }, effect: 'harvest' },
  { id: 'taoyuan', label: '桃园结义', kind: 'trick', play: { targeting: 'none', scope: 'all' }, effect: 'recoverOne' },
  { id: 'nanman', label: '南蛮入侵', kind: 'trick', play: { targeting: 'none', scope: 'others' }, effect: 'requireSha' },
  { id: 'wanjian', label: '万箭齐发', kind: 'trick', play: { targeting: 'none', scope: 'others' }, effect: 'requireShan' },
  { id: 'wuzhong', label: '无中生有', kind: 'trick', play: { targeting: 'none', scope: 'self' }, effect: 'drawTwo' },
  { id: 'juedou', label: '决斗', kind: 'trick', play: { targeting: 'single', scope: 'selected' }, effect: 'duel' },
  { id: 'shunshou', label: '顺手牵羊', kind: 'trick', play: { targeting: 'single', targetRule: 'distance1Stealable', scope: 'selected' }, effect: 'gainZone' },
  { id: 'guohe', label: '过河拆桥', kind: 'trick', play: { targeting: 'single', targetRule: 'stealable', scope: 'selected' }, effect: 'discardZone' },
  { id: 'jiedao', label: '借刀杀人', kind: 'trick', play: { targeting: 'borrowed', targetRule: 'armed', scope: 'selected' }, effect: 'borrowed' },
  { id: 'wuxie', label: '无懈可击', kind: 'trick', play: { targeting: 'unplayable' }, effect: 'none' },
  { id: 'lebu', label: '乐不思蜀', kind: 'delay', play: { targeting: 'single', targetRule: 'uniqueTargetJudge', scope: 'selected' }, effect: 'delay' },
  { id: 'shandian', label: '闪电', kind: 'delay', play: { targeting: 'none', availability: 'uniqueSelfJudge', scope: 'self' }, effect: 'delay' },
] as const;
